
background_opacity 0.85
font_size 13.0
font_family JetBrainsMono Nerd Font

# --- tmux pane resizing support ---
map alt+shift+left  send_text all \x1b[1;4D
map alt+shift+right send_text all \x1b[1;4C
map alt+shift+up    send_text all \x1b[1;4A
map alt+shift+down  send_text all \x1b[1;4B

