# TERMINAL (KITTY + GNOME)
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-kitty:RGB'
set -g set-clipboard on

# PREFIX
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# COPY MODE (VIM)
setw -g mode-keys vi
bind-key -T copy-mode-vi Space send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key p run "wl-paste | tmux load-buffer - && tmux paste-buffer"

# PANE RESIZE
bind -n M-S-Left resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up resize-pane -U 2
bind -n M-S-Down resize-pane -D 2

# GENERAL
set -g mouse on
set-option -g history-limit 64096
set -sg escape-time 10

# TITLES
set -g set-titles on
set -g set-titles-string "#T"

source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

