-- return {
--   {
--     "CopilotC-Nvim/CopilotChat.nvim",
--     dependencies = {
--       { "zbirenbaum/copilot.lua" },
--       { "nvim-lua/plenary.nvim" },
--     },
--     build = "make tiktoken",
--     opts = {
--       window = {
--         layout = "vertical",
--       },
--     },
--     keys = {
--       {
--         "<leader>cp",
--         "<cmd>CopilotChat<CR>",
--         mode = "n",
--         desc = "Copilot Chat",
--       },
--       {
--         "<leader>cp",
--         "<cmd>CopilotChat<CR>",
--         mode = "v",
--         desc = "Copilot Chat (Visual)",
--       },
--     },
--   },
-- }
